version: '3'

services: 
  web:
    build: 
      context: .
      dockerfile: ServiceAPI\Dockerfile
    command: "dotnet ef database update"
    ports:
      - 3500:80
    restart: on-failure
    depends_on: 
      - postgres
      - rabbitmq
  
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
    