version: '3'

services: 
  web:
    build: 
      context: .
      dockerfile: ServiceAPI\Dockerfile
    command: "dotnet ef database update"
    ports:
      - 3500:80
    depends_on: 
      - postgres
      - rabbitmq
  
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    
    ports:
      - 5672:5672
      - 15672:15672
    